MyChatApp/Models/Chat.cs
namespace MyChatApp.Models
{
    public class Chat
    {
        public Chat()
        {
            Messages = new List<Message>();
            Users = new List<ChatUser>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public ChatType Type { get; set; }
        public ICollection<Message> Messages { get; set; }
        public ICollection<ChatUser> Users { get; set; }
    }
}

MyChatApp/Models/ChatType.cs
namespace MyChatApp.Models
{
    public enum ChatType
    {
        Room,
        Private
    }
}

MyChatApp/Models/ChatUser.cs
using Microsoft.AspNetCore.Identity;

namespace MyChatApp.Models
{
    public class ChatUser
    {
        public string UserId {  get; set; }
        public User User { get; set; }

        public int ChatId { get; set; }
        public Chat Chat { get; set; }
        public UserRole Role { get; set; }
    }
}

MyChatApp/Models/ErrorViewModel.cs
namespace MyChatApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyChatApp/Models/Message.cs
using Microsoft.AspNetCore.Identity;

namespace MyChatApp.Models
{
    public class Message
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public DateTime Timestamp { get; set; }

        public int ChatId { get; set; }
        public Chat Chat { get; set; }
    }

}

MyChatApp/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace MyChatApp.Models
{
    public class User : IdentityUser
    {
        public User() : base()
        {
            Chats = new List<ChatUser>();
        }
        public ICollection<ChatUser> Chats { get; set; }
    }
}

MyChatApp/Models/UserRole.cs
namespace MyChatApp.Models
{
    public enum UserRole
    {
        Admin,
        Member,
        Guest
    }
}

MyChatApp/Controllers/AccountController.cs
using System.Threading.Tasks;
using MyChatApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MyChatApp.Controllers
{
    public class AccountController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;

        public AccountController(
            UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login() => View();
        [HttpPost]

        public async Task<IActionResult> Login(string username, string password)
        {
            var user = await _userManager.FindByNameAsync(username);

            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, password, false, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public IActionResult Register() => View();
        [HttpPost]

        public async Task<IActionResult> Register(string username, string password)
        {
            var user = new User
            {
                UserName = username
            };

            var result = await _userManager.CreateAsync(user, password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Register", "Account");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login", "Account");
        }
    }
}

MyChatApp/Controllers/ConfigController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MyChatApp.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ConfigController : ControllerBase
    {
        private readonly IConfiguration _configuration;

        public ConfigController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet("secrets")]
        public IActionResult GetSecrets()
        {
            var secrets = new
            {
                Endpoint = _configuration["ENDPOINT"],
                ApiKey = _configuration["KEY"]
            };

            return Ok(secrets); // Be careful about exposing sensitive info
        }
    }

}

MyChatApp/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MyChatApp.Database;
using MyChatApp.Hubs;
using MyChatApp.Infrastructure;
using MyChatApp.Infrastructure.Repository;
using MyChatApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;


namespace MyChatApp.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        private IChatRepository _repo;
        public HomeController(IChatRepository repo) => _repo = repo;
        public IActionResult Index()
        {
            var chats = _repo.GetChats(GetUserId());

            return View(chats);
        }

        public IActionResult Find([FromServices] AppDbContext ctx)
        {
            var users = ctx.Users
                .Where(x => x.Id != User.GetUserId())
                .ToList();

            return View(users);
        }

        public IActionResult Private()
        {
            var chats = _repo.GetPrivateChats(GetUserId());

            return View(chats);
        }

        public async Task<IActionResult> CreatePrivateRoom(string userId)
        {
            var id = await _repo.CreatePrivateRoom(GetUserId(), userId);

            return RedirectToAction("Chat", new { id });
        }

        [HttpGet("{id}")]
        public IActionResult Chat(int id)
        {
            return View(_repo.GetChat(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoom(string name)
        {
            await _repo.CreateRoom(name, GetUserId());
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> JoinRoom(int id)
        {
            await _repo.JoinRoom(id, GetUserId());

            return RedirectToAction("Chat", "Home", new { id = id });
        }

        public async Task<IActionResult> SendMessage(
            int roomId,
            string message,
            [FromServices] IHubContext<ChatHub> chat)
        {
            var Message = await _repo.CreateMessage(roomId, message, User.Identity.Name);

            await chat.Clients.Group(roomId.ToString())
                .SendAsync("RecieveMessage", new
                {
                    Text = Message.Text,
                    Name = Message.Name,
                    Timestamp = Message.Timestamp.ToString("hh:mm")
                });

            return Ok();
        }
    }
}

MyChatApp/ViewComponents/RoomViewComponent.cs
using System.Linq;
using System.Security.Claims;
using MyChatApp.Database;
using MyChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace MyChatApp.ViewComponents
{
    [Authorize]
    public class RoomViewComponent : ViewComponent
    {
        private AppDbContext _ctx;

        public RoomViewComponent(AppDbContext ctx)
        {
            _ctx = ctx;
        }

        public IViewComponentResult Invoke()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if(_ctx.Users.Count() != 0)
            {
                var userName = _ctx.Users.FirstOrDefault(u => u.Id == userId).UserName;
                ViewBag.userName = userName;
            }
            

            var chats = _ctx.ChatUsers
                .Include(x => x.Chat)
                .Where(x => x.UserId == userId
                    && x.Chat.Type == ChatType.Room)
                .Select(x => x.Chat)
                .ToList();

            return View(chats);
        }
    }
}

MyChatApp/Views/Home/Chat.cshtml
@model Chat

<div class="chat-body">
    @foreach (var message in Model.Messages)
    {
        <div class="message">
            <header>@message.Name:</header>
            <p>@message.Text</p>
            <footer>@message.Timestamp.ToString("hh:mm")</footer>
        </div>
    }
</div>
<form class="chat-input bg-dark" onsubmit="sendMessage(event)" asp-controller="Home" asp-action="CreateMessage">
    <input type="hidden" name="roomId" value="@Model.Id">
    <input type="text" name="message" id="message-input">
    <button class="btn btn-outline-info" type="submit" id="send-btn">Send</button>
</form>

@section scripts {
    <script src="~/js/signalr.min.js"></script>
    <script src="~/js/messageBuilder.js"></script>
    <script src="~/js/azure.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/chatHub")
            .build();

        var _connectionId = '';

        connection.on("RecieveMessage", function (data) {
            var message = messageBuilder()
                .createMessage()
                .withHeader(data.name)
                .withParagraph(data.text)
                .withFooter(data.timestamp)
                .build();

            document.querySelector('.chat-body').append(message);
        })

        connection.start()
            .then(function () {
                connection.invoke('joinRoom', '@Model.Id');
            })
            .catch(function (err) {
                console.log(err)
            })

        window.addEventListener('onunload', function () {
            connection.invoke('leaveRoom', '@Model.Id');
        })

        var sendMessage = function (event) {
            event.preventDefault();

            var data = new FormData(event.target);
            document.getElementById('message-input').value = '';
            axios.post('/Home/SendMessage', data)
                .then(res => {
                    console.log("Message Sent!")
                })
                .catch(err => {
                    console.log("Failed to send message!")
                })
        }

    </script>
}

MyChatApp/Views/Home/Find.cshtml
@model IEnumerable<User>



<ul class="list-group">
    @foreach (var user in Model)
    {

        <div class="list-group-item">
            <a class="list-item" asp-controller="Home" asp-action="CreatePrivateRoom" asp-route-userId="@user.Id">
                @user.UserName
            </a>
        </div>
    }
</ul>

MyChatApp/Views/Home/Index.cshtml
@model IEnumerable<Chat>

<div class="chat-body">
    @foreach (var chat in Model)
    {
        <a class="btn btn-info" style="margin: 20px 70px 20px 70px;" asp-controller="Home" asp-action="JoinRoom" asp-route-id="@chat.Id">
            @chat.Name
        </a>
    }
</div>

MyChatApp/Views/Home/Private.cshtml
@model IEnumerable<Chat>

@{
    var userId = User.GetUserId();
}

<div class="chat-body">
    @foreach (var chat in Model)
    {
        <a class="btn btn-info" style="margin: 20px 70px 20px 70px;"  asp-controller="Home" asp-action="Chat" asp-route-id="@chat.Id">
            @chat.Users.FirstOrDefault(x => x.UserId != userId).User.UserName
        </a>
    }
</div>

MyChatApp/Views/Shared/Components/Room/Default.cshtml
@model IEnumerable<Chat>


<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 240px;">
    <ul class="nav nav-pills flex-column mb-auto">
        @foreach (var chat in Model)
        {
            <hr />
            <li>
                <a class="nav-link text-white" asp-controller="Home" asp-action="Chat" asp-route-id="@chat.Id">
                    @chat.Name
                </a>
            </li>
            <hr />
        }
        <li class="nav-item">
            <a class="nav-link text-white" aria-current="page" id="create-room-btn" href="#">
            <strong>Add room</strong>
        </a>
        </li>
    </ul>
    <hr />
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <strong>@ViewBag.userName</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</div>

MyChatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatApp</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css">



</head>

<body>

    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid justify-content-start">
            <a class="navbar-brand text-light" href="#">Messenger</a>
            <a class="btn btn-sm btn-outline-secondary" style="margin-left:8rem; margin-right: 1rem;" asp-controller="Home" asp-action="Index">Home</a>
            <a class="btn btn-sm btn-outline-secondary" style="margin-right: 1rem;" asp-controller="Home" asp-action="Find">Find</a>
            <a class="btn btn-sm btn-outline-secondary" style="margin-right: 1rem;" asp-controller="Home" asp-action="Private">Private</a>
        </div>
        
    </nav>

    <div class="main">
        @if (User.Identity.IsAuthenticated)
        {
            @* <vc:room></vc:room> *@
            @if (User.Identity.IsAuthenticated)
            {
                @await Component.InvokeAsync("Room")
            }
        }
        <div class="chat">
            @RenderBody()
        </div>
    </div>

    <div class="modal" id="create-room-modal">
        <form asp-controller="Home" asp-action="CreateRoom" class="modal-body bg-info">
            <button type="button" class="close" onclick="closeModal()">X</button>
            <header>Create Room</header>
            <div>
                <input name="name">
            </div>
            <footer>
                <button class="btn btn-dark">Create</button>
            </footer>
        </form>
    </div>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</html>